version: '2'
services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php:php
        volumes:
            - ./log/nginx/:/var/log/nginx
            - ./nginx/sites:/etc/nginx/conf.d
            - ./www:/var/www

    php:
        build: ./php
        ports:
            - "9000:9000"
        expose:
            - '9000'
        volumes:
            - ./www:/var/www
        links:
            - mariadb:mariadb
            - memcached:memcached
            - redis:redis
            - elasticsearch:elasticsearch

    mariadb:
        image: mariadb
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: toor
        volumes:
            - ./log/mariadb:/var/log/mysql
            - ./data/mariadb:/var/lib/mysql

    memcached:
        image: memcached
        ports:
            - "11211:11211"

    redis:
        image: redis
        ports:
            - "6379:6379"

    maildev:
        image: djfarrelly/maildev
        ports:
            - "1080:80"

    elasticsearch:
        image: elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"